### ISSUE TITLE
New items that affect burden.

### ISSUE THREAD

**Issue by Selindrile** [nitrous24/Lua#83]
Not sure if you're still maintaining this addon but...

threshItems should add the following entries to track their effect on burden.

,[26933]=40 -- Kara. Farsetto +1
,[26932]=40 -- Kara. Farsetto

**Comment by nitrous24** [comment]
I am not playing the game anymore and haven't really been keeping up on my addons. I would say the best place to put this would be in the main windower lua section:  https://github.com/Windower/Lua

I did however add them and open a pull request since it's not that big of a problem to add it. Hopefully they notice it and it'll get added in soon.

**Comment by Selindrile** [comment]
For what it's worth, I actually did post this there, and was told it wasn't their addon :( so I guess nobody has taken it over, thanks though.

**Comment by Selindrile** [comment]
Thanks, I had posted it on Byrth's and when he said it wasn't his I tracked you down.
